config/routes.rb
Rails.application.routes.draw do
  root 'store#index', as: 'store'
  resources :wallets, only: [:show, :edit, :update, :destroy]
  resources :products, only: [:show]
  resources :line_items, only: [:index]
  resources :comments, only: [:show, :edit, :update, :destroy]
  resources :categories, only: [:show, :index]
  resources :carts, only: [:index]
  devise_for :users, :controllers => { registration: 'registration' }
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :items, through: :line_items
end

app/models/cart_item.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :items, through: :line_items
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :product
    has_many :users, through: :products



validates :description, length: { maximum: 1500, too_long: "%{count} characters is the maximum allowed. "}
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :item 
    belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :cart
    has_many :products, through: :cart
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :line_items

end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, through: :cart 
  has_many :comments, through: :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wallet.rb
class Wallet < ApplicationRecord
    belongs_to :user
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @comments = Comment.all.order("created_at desc")
  end

  def show
  end

  def new
    @comment = current_user.comments.build
  end

  def edit
  end

  def create
    @comment = current_user.comments.build(comment_params)
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'Instrument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  
  def comment_params
    params.require(:comment).permit(:description)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/waller_helper.rb
module WallerHelper
end

app/helpers/wallet_helper.rb
module WalletHelper
end

app/views/comment/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @comments, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', comments_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/comment/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Comment
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', comment: @comment%>
</div>

app/views/comment/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest comments
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="comment-index-grid pt4">
  <% @comments.each do |comment| %>

    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to comment.title, comment %></h3>

      <p class="has-text-gray fg pt1">Commented by <%= comment.user.email %></p>


      <% if comment_author(comment) %>
         <%= link_to 'Edit', edit_comment_path(comment), class: "button is-small" %>
         <%= link_to 'Delete', comment, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/comment/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Make a comment
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', comment: @comment %>
</div>

app/views/comment/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section comment-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @comment.id %></h1>


      <h3 class="subtitle is-4">Description</h3>
      <%= @comment.description %>


    
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered">Comments/h4>
        <p class="has-text-centered mb4">Commented by <%= @instrument.user.name %></p>
      </div>
    </div>
  </div>

  <% if comment_author(@comment) %>
    <%= link_to 'Edit', edit_comment_path(@comment), class: 'button' %>
  <% end %>
</section>