config/routes.rb
Rails.application.routes.draw do
  root 'store#index', as: 'store'
  resources :wallets, only: [:show, :edit, :update, :destroy]
  resources :products, only: [:show]
  resources :line_items, only: [:index]
  resources :comments, only: [:show, :edit, :update, :destroy]
  resources :categories, only: [:show, :index]
  resources :carts, only: [:index]
  devise_for :users, :controllers => { registration: 'registration' }
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :items, through: :line_items
end

app/models/cart_item.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :items, through: :line_items
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :product
    has_many :users, through: :products



validates :description, length: { maximum: 1500, too_long: "%{count} characters is the maximum allowed. "}
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :item 
    belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :cart
    has_many :products, through: :cart
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :line_items

end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, through: :cart 
  has_many :comments, through: :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wallet.rb
class Wallet < ApplicationRecord
    belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:checkout, :show]

  def index
  end

  def show
  end

  def checkout
    @order = Order.create_from_cart(@cart)
    @order.change_order_status
    @order.change_inventory
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to order_path(@order), notice: 'Thanks for your order!' }
    end
  end

  private
  def set_cart
    @cart = Cart.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/waller_helper.rb
module WallerHelper
end

app/helpers/wallet_helper.rb
module WalletHelper
end

app/views/cart/index.html.erb
<h1>Cart#index</h1>
<p>Find me in app/views/cart/index.html.erb</p>

app/views/cart/show.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
      <h2>Your Cart</h2>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
              <th class="text-center">Price</th>
              <th class="text-center">Total</th>
            </tr>
          </thead>
      <% current_cart.line_items.each do |line_item| %>
        <tbody>
          <tr>
            <td class="col-sm-8 col-md-6">
              <h4 class="media-heading"><%= link_to line_item.product.title, product_path(line_item.item) %></h4>
            </td>
            <td class="col-sm-1 col-md-1" style="text-align: center">
            <input type="text" class="form-control" id="exampleInputEmail1" value="<%= line_item.quantity %>" data-id="<%= line_item.id %>">
            </td>
            <td class="col-sm-1 col-md-1 text-center" id="price"><%= line_item.product.price %></td>
            <td class="col-sm-1 col-md-1 text-center" id="sub-total"><%= (line_item.quantity * line_item.product.price)) %></td>
            <td>
            </td>
          </tr>
      <% end %>
            <tr>
              <td>   </td>
              <td>   </td>
              <td>   </td>
              <td><h3>Total</h3></td>
              <td class="text-right"><h3 class="total"><strong><strong><%= number_to_currency(to_currency(current_cart.total)) %></strong></h3></td>
            </tr>
            <tr>
              <td>   </td>
              <td>   </td>
              <td>   </td>
              <td>
              <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span><%= link_to " Continue Shopping", store_path %>
              </button></td>
              <td id="stripe-button">
                <%= render 'carts/stripe_modal' %>
              </td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>